language: node_js
node_js:
  - "11.10"
# node_modules cache
cache:
  directories:
    - node_modules
if: branch = master
script:
  - git checkout $TRAVIS_BRANCH
  - git remote set-url origin https://sergeevNick:$GITHUB_API_KEY@github.com/eigen-space/helper-scripts.git
  - chmod +x ./scripts/ci/jenkins-commit-checker.sh && ./scripts/ci/jenkins-commit-checker.sh && npm deploy:publish