language: node_js
node_js:
  - "11.10"
# node_modules cache
cache: yarn
script:
  - git config --global github.user sergeevNick
  - git config --global github.token $GITHUB_API_KEY
  - git checkout $TRAVIS_BRANCH
  - yarn deploy:publish