language: node_js
node_js:
  - "11.10"
git:
  depth: false
# node_modules cache
cache:
  directories:
    - node_modules
if: branch = master
script:
  - git checkout $TRAVIS_BRANCH
  - git remote set-url origin https://sergeevNick:$GITHUB_API_KEY@github.com/eigen-space/helper-scripts.git
  - chmod +x ./scripts/ci/detect-autocommit.sh
  - return 1;
  - if ./scripts/ci/detect-autocommit.sh ; then
      npm run deploy:publish;
    fi
notifications:
  slack:
    rooms:
      - eigenspaceworkspace:kmQErenC9R4KA4kWyb1j8UaS#ci
    on_success: change
    on_failure: always
